#!/usr/bin/env bash

MODULE_NAME=server

rm -rf dist/*
esbuild src/index.ts --bundle \
  --external:fastify \
  --external:\@simplyhexagonal/logger \
  --external:\@simplyhexagonal/mono-context \
  --platform=node \
  --outfile=dist/$MODULE_NAME.js --sourcemap --format=cjs \
  && tsc -d --emitDeclarationOnly --rootDir src --outDir dist \
  && mv dist/index.d.ts dist/$MODULE_NAME.d.ts \
  || exit 1
